package org.vitrivr.cottontail.dbms.index.lucene

import jetbrains.exodus.env.Transaction
import jetbrains.exodus.vfs.VirtualFileSystem
import org.apache.lucene.analysis.standard.StandardAnalyzer
import org.apache.lucene.index.Term
import org.apache.lucene.queryparser.flexible.standard.QueryParserUtil
import org.apache.lucene.search.*
import org.vitrivr.cottontail.core.basics.Cursor
import org.vitrivr.cottontail.core.database.ColumnDef
import org.vitrivr.cottontail.core.database.TupleId
import org.vitrivr.cottontail.core.queries.binding.Binding
import org.vitrivr.cottontail.core.queries.binding.BindingContext
import org.vitrivr.cottontail.core.queries.binding.MissingTuple
import org.vitrivr.cottontail.core.queries.predicates.BooleanPredicate
import org.vitrivr.cottontail.core.queries.predicates.ComparisonOperator
import org.vitrivr.cottontail.core.tuple.StandaloneTuple
import org.vitrivr.cottontail.core.tuple.Tuple
import org.vitrivr.cottontail.core.values.DoubleValue
import org.vitrivr.cottontail.core.values.StringValue
import org.vitrivr.cottontail.core.values.Value
import org.vitrivr.cottontail.core.values.pattern.LikePattern
import org.vitrivr.cottontail.dbms.exceptions.QueryException
import org.vitrivr.cottontail.dbms.index.pq.PQIndexCursor
import org.vitrivr.cottontail.storage.lucene.XodusDirectory

/**
 * A [Cursor] implementation for the [LuceneIndex].
 *
 * @author Ralph Gasser
 * @version 1.0.0
 */
class LuceneCursor(index: LuceneIndex.Tx, context: BindingContext, val predicate: BooleanPredicate): Cursor<Tuple> {
    /** The sub-transaction used by this [PQIndexCursor]. */
    private val xodusTx: Transaction = index.xodusTx.readonlySnapshot

    /** The [VirtualFileSystem] used by this [LuceneIndex]. */
    private val vfs = VirtualFileSystem(this.xodusTx.environment);

    /** The [ColumnDef] generated by this [Cursor]. */
    private val columns = index.columnsFor(predicate).toTypedArray()

    /** The [ColumnDef] indexed by the [LuceneIndex.Tx] backing this [LuceneCursor]. */
    private val queryColumns: Array<ColumnDef<*>> = index.columns

    /** The [LuceneIndexDataStore] backing this [LuceneIndex]. */
    private var store = LuceneIndexDataStore(XodusDirectory(this.vfs, index.dbo.name.toString(), this.xodusTx), this.queryColumns[0].name)

    /** Number of [TupleId]s returned by this [Iterator]. */
    @Volatile
    private var returned = 0

    /** Lucene [Query] representation of [BooleanPredicate] . */
    private val query: Query = this.predicate.toLuceneQuery(context)

    /** [IndexSearcher] instance used for lookup. */
    private val searcher = IndexSearcher(this.store.indexReader)

    /* Execute query and add results. */
    private val results = this.searcher.search(this.query, Integer.MAX_VALUE)

    override fun moveNext(): Boolean {
        return this.returned < this.results.totalHits.value
    }

    override fun key(): TupleId {
        val scores = this.results.scoreDocs[this.returned]
        val doc = this.searcher.doc(scores.doc)
        return doc[LuceneIndex.TID_COLUMN].toLong()
    }

    override fun value(): Tuple {
        val scores = this.results.scoreDocs[this.returned++]
        val doc = this.searcher.doc(scores.doc)
        return StandaloneTuple(doc[LuceneIndex.TID_COLUMN].toLong(), this.columns, arrayOf(DoubleValue(scores.score)))
    }

    override fun close() {
        this.store.close()
        this.xodusTx.abort()
    }

    /**
     * Converts a [BooleanPredicate] to a [Query] supported by Apache Lucene.
     *
     * @return [Query]
     */

    private fun BooleanPredicate.toLuceneQuery(context: BindingContext): Query = with(context) {
        with(MissingTuple) {
            when (this@toLuceneQuery) {
                is BooleanPredicate.Comparison -> {
                    val op = this@toLuceneQuery.operator
                    val left = op.left
                    val right = op.right
                    val column = if (right is Binding.Column && right.column == this@LuceneCursor.queryColumns[0]) {
                        right.column
                    } else if (left is Binding.Column && left.column == this@LuceneCursor.queryColumns[0]) {
                        left.column
                    } else {
                        throw QueryException("Conversion to Lucene query failed: One side of the comparison operator must be a column value!")
                    }
                    val literal: Value = if (right is Binding.Literal) {
                        right.getValue() ?: throw QueryException("Conversion to Lucene query failed: Literal value cannot be null!")
                    } else if (left is Binding.Literal) {
                        right.getValue() ?: throw QueryException("Conversion to Lucene query failed: Literal value cannot be null!")
                    } else {
                        throw QueryException("Conversion to Lucene query failed: One side of the comparison operator must be a literal value!")
                    }

                    return when (op) {
                        is ComparisonOperator.Equal -> {
                            if (literal is StringValue) {
                                TermQuery(Term("${column.name}_str", literal.value))
                            } else {
                                throw QueryException("Conversion to Lucene query failed: EQUAL queries strictly require a StringValue as second operand!")
                            }
                        }

                        is ComparisonOperator.Like -> {
                            when (literal) {
                                is StringValue -> QueryParserUtil.parse(
                                    arrayOf(literal.value),
                                    arrayOf("${column.name}_txt"),
                                    StandardAnalyzer()
                                )

                                is LikePattern -> QueryParserUtil.parse(
                                    arrayOf(literal.toLucene().pattern),
                                    arrayOf("${column.name}_txt"),
                                    StandardAnalyzer()
                                )

                                else -> throw throw QueryException("Conversion to Lucene query failed: LIKE queries require a StringValue OR LikePatternValue as second operand!")
                            }
                        }

                        is ComparisonOperator.Match -> {
                            if (literal is StringValue) {
                                QueryParserUtil.parse(arrayOf(literal.value), arrayOf("${column.name}_txt"), StandardAnalyzer())
                            } else {
                                throw throw QueryException("Conversion to Lucene query failed: MATCH queries strictly require a StringValue as second operand!")
                            }
                        }

                        else -> throw QueryException("Lucene Query Conversion failed: Only EQUAL, MATCH and LIKE queries can be mapped to a Apache Lucene!")
                    }
                }

                is BooleanPredicate.And -> BooleanQuery.Builder().add(this@toLuceneQuery.p1.toLuceneQuery(context), BooleanClause.Occur.MUST).add(this@toLuceneQuery.p2.toLuceneQuery(context), BooleanClause.Occur.MUST)
                is BooleanPredicate.Or -> BooleanQuery.Builder().add(this@toLuceneQuery.p1.toLuceneQuery(context), BooleanClause.Occur.SHOULD).add(this@toLuceneQuery.p2.toLuceneQuery(context), BooleanClause.Occur.SHOULD)
                else -> throw IllegalArgumentException("LuceneIndex can only process AND and OR predicates.")
            }
        }
    }.build()
}