package org.vitrivr.cottontail.database.queries.planning.nodes.logical.projection

import org.vitrivr.cottontail.database.column.ColumnDef
import org.vitrivr.cottontail.database.queries.OperatorNode
import org.vitrivr.cottontail.database.queries.planning.nodes.logical.UnaryLogicalOperatorNode
import org.vitrivr.cottontail.database.queries.projection.Projection
import org.vitrivr.cottontail.model.basics.Name
import org.vitrivr.cottontail.model.basics.Type

/**
 * A [UnaryLogicalOperatorNode] that represents a projection operation involving aggregate functions such as [Projection.EXISTS].
 *
 * @author Ralph Gasser
 * @version 1.0.0
 */
class ExistsProjectionLogicalOperatorNode(input: OperatorNode.Logical, val fields: List<Pair<Name.ColumnName, Name.ColumnName?>>) : UnaryLogicalOperatorNode(input) {

    /** The [Projection] represented by this [ExistsProjectionLogicalOperatorNode]. */
    val type: Projection = Projection.EXISTS

    /** The [ColumnDef] generated by this [ExistsProjectionLogicalOperatorNode]. */
    override val columns: Array<ColumnDef<*>>

    /** The [ColumnDef] required by this [ExistsProjectionLogicalOperatorNode]. */
    override val requires: Array<ColumnDef<*>> = emptyArray()

    init {
        /* Calculate necessary fields. */
        val alias = fields.first().second
        val name = alias ?: (input.columns.first().name.entity()?.column(Projection.EXISTS.label()) ?: Name.ColumnName(Projection.EXISTS.label()))
        this.columns = arrayOf(ColumnDef(name, Type.Boolean, false))
    }

    /**
     * Returns a copy of this [ExistsProjectionLogicalOperatorNode] and its input.
     *
     * @return Copy of this [ExistsProjectionLogicalOperatorNode] and its input.
     */
    override fun copyWithInputs() = ExistsProjectionLogicalOperatorNode(this.input.copyWithInputs(), this.fields)

    /**
     * Returns a copy of this [ExistsProjectionLogicalOperatorNode] and its output.
     *
     * @param input The [OperatorNode.Logical] that should act as inputs.
     * @return Copy of this [ExistsProjectionLogicalOperatorNode] and its output.
     */
    override fun copyWithOutput(input: OperatorNode.Logical?): OperatorNode.Logical {
        require(input != null) { "Input is required for unary logical operator node." }
        val projection = ExistsProjectionLogicalOperatorNode(input, this.fields)
        return (this.output?.copyWithOutput(projection) ?: projection)
    }

    /**
     * Returns a [ExistsProjectionPhysicalOperatorNode] representation of this [ExistsProjectionLogicalOperatorNode]
     *
     * @return [ExistsProjectionPhysicalOperatorNode]
     */
    override fun implement(): Physical = TODO()

    /**
     * Compares this [ExistsProjectionLogicalOperatorNode] to another object.
     *
     * @param other The other [Any] to compare this [ExistsProjectionLogicalOperatorNode] to.
     * @return True if other equals this, false otherwise.
     */
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other !is ExistsProjectionLogicalOperatorNode) return false

        if (type != other.type) return false
        if (fields != other.fields) return false

        return true
    }

    /**
     * Generates and returns a hash code for this [ExistsProjectionLogicalOperatorNode].
     */
    override fun hashCode(): Int {
        var result = this.type.hashCode()
        result = 31 * result + this.fields.hashCode()
        return result
    }
}