package org.vitrivr.cottontail.database.queries.planning.nodes.physical.projection

import org.vitrivr.cottontail.database.column.ColumnDef
import org.vitrivr.cottontail.database.queries.OperatorNode
import org.vitrivr.cottontail.database.queries.QueryContext
import org.vitrivr.cottontail.database.queries.planning.cost.Cost
import org.vitrivr.cottontail.database.queries.planning.nodes.physical.UnaryPhysicalOperatorNode
import org.vitrivr.cottontail.database.queries.projection.Projection
import org.vitrivr.cottontail.execution.TransactionContext
import org.vitrivr.cottontail.execution.operators.basics.Operator
import org.vitrivr.cottontail.execution.operators.projection.*
import org.vitrivr.cottontail.model.basics.Name
import org.vitrivr.cottontail.model.exceptions.QueryException

/**
 * A [UnaryPhysicalOperatorNode] that represents a projection operation involving aggregate functions such as [Projection.MAX], [Projection.MIN] or [Projection.SUM].
 *
 * @author Ralph Gasser
 * @version 2.1.0
 */
class AggregatingProjectionPhysicalOperatorNode(input: OperatorNode.Physical? = null, type: Projection, fields: List<Pair<Name.ColumnName, Name.ColumnName?>>) : AbstractProjectionPhysicalOperatorNode(input, type, fields) {

    /** The [ColumnDef] generated by this [AggregatingProjectionPhysicalOperatorNode]. */
    override val columns: Array<ColumnDef<*>>
        get() = this.fields.map {
            val inColumn = this.input?.columns?.find { c -> c.name == it.first } ?: throw QueryException.QueryBindException("Column with name $it could not be found on input.")
            val outColumn = inColumn.copy(name = it.second ?: inColumn.name)
            if (!inColumn.type.numeric) throw QueryException.QueryBindException("Projection of type ${this.type} can only be applied to numeric column, which $inColumn isn't.")
            outColumn
        }.toTypedArray()

    /** The [ColumnDef] required by this [AggregatingProjectionPhysicalOperatorNode]. */
    override val requires: Array<ColumnDef<*>>
        get() = this.fields.map {
            this.input?.columns?.find { c -> c.name == it.first } ?: throw QueryException.QueryBindException("Column with name $it could not be found on input.")
        }.toTypedArray()

    /** The output size of this [AggregatingProjectionPhysicalOperatorNode] is always one. */
    override val outputSize: Long = 1

    /** The [Cost] of a [AggregatingProjectionPhysicalOperatorNode]. */
    override val cost: Cost
        get() = Cost(cpu = 3 * Cost.COST_MEMORY_ACCESS + Cost.COST_FLOP) * (this.input?.outputSize ?: 0)

    init {
        /* Sanity check. */
        require(this.type in arrayOf(Projection.MIN, Projection.MAX, Projection.MAX, Projection.SUM)) {
            "Projection of type ${this.type} cannot be used with instances of AggregatingProjectionPhysicalOperatorNode."
        }
    }

    /**
     * Creates and returns a copy of this [AggregatingProjectionPhysicalOperatorNode] without any children or parents.
     *
     * @return Copy of this [AggregatingProjectionPhysicalOperatorNode].
     */
    override fun copy() = AggregatingProjectionPhysicalOperatorNode(type = this.type, fields = this.fields)

    /**
     * Partitions this [AggregatingProjectionPhysicalOperatorNode].
     *
     * @param p The number of partitions to create.
     * @return List of [OperatorNode.Physical], each representing a partition of the original tree.
     */
    override fun partition(p: Int): List<Physical> {
        throw UnsupportedOperationException("AggregatingProjectionPhysicalOperatorNode cannot be partitioned.")
    }

    /**
     * Converts this [CountProjectionPhysicalOperatorNode] to a [CountProjectionOperator].
     *
     * @param tx The [TransactionContext] used for execution.
     * @param ctx The [QueryContext] used for the conversion (e.g. late binding).
     */
    override fun toOperator(tx: TransactionContext, ctx: QueryContext): Operator {
        val `in` = this.input?.toOperator(tx, ctx) ?: throw IllegalStateException("Cannot convert disconnected OperatorNode to Operator (node = $this)")
        return when (this.type) {
            Projection.SUM -> SumProjectionOperator(`in`, this.fields)
            Projection.MAX -> MaxProjectionOperator(`in`, this.fields)
            Projection.MIN -> MinProjectionOperator(`in`, this.fields)
            Projection.MEAN -> MeanProjectionOperator(`in`, this.fields)
            else -> throw IllegalStateException("An AggregatingProjectionPhysicalOperatorNode requires a project of type SUM, MAX, MIN or MEAN but encountered ${this.type}.")
        }
    }

    /**
     * Compares this [AggregatingProjectionPhysicalOperatorNode] to another object.
     *
     * @param other The other [Any] to compare this [AggregatingProjectionPhysicalOperatorNode] to.
     * @return True if other equals this, false otherwise.
     */
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other !is AggregatingProjectionPhysicalOperatorNode) return false

        if (type != other.type) return false
        if (fields != other.fields) return false

        return true
    }

    /**
     * Generates and returns a hash code for this [AggregatingProjectionPhysicalOperatorNode].
     */
    override fun hashCode(): Int {
        var result = this.type.hashCode()
        result = 31 * result + this.fields.hashCode()
        return result
    }
}